//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rgpharmacyy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Covid_essentials
    {
        public int prid { get; set; }
        public string pname { get; set; }
        public string cname { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string img { get; set; }
        public string describe { get; set; }
    }
}
