//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rgpharmacyy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int uid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string phone_no { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string address { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
